name: CI — Build & Test (Backend & Frontend)

on:
  pull_request:
    branches: [ dev, main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"
  push:
    branches: [ "feat/**", "fix/**" ]
    paths:
      - "backend/**"
      - "frontend/**"

permissions:
  contents: read
  id-token: write    # for OIDC login to Azure (no stored creds)
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}

jobs:
  build-test-push:
    name: ${{ matrix.svc }} CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [ "product_service", "order_service", "frontend" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set service paths
        id: paths
        run: |
          if [[ "${{ matrix.svc }}" == "frontend" ]]; then
            echo "dir=frontend" >> $GITHUB_OUTPUT
            echo "image=frontend" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.svc }}" == "product_service" ]]; then
            echo "dir=backend/product_service" >> $GITHUB_OUTPUT
            echo "image=product-service" >> $GITHUB_OUTPUT
          else
            echo "dir=backend/order_service" >> $GITHUB_OUTPUT
            echo "image=order-service" >> $GITHUB_OUTPUT
          fi

      - name: Cache node_modules (frontend only)
        if: matrix.svc == 'frontend'
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.paths.outputs.dir }}/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', steps.paths.outputs.dir)) }}

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build & unit tests (if any)
        run: |
          cd "${{ steps.paths.outputs.dir }}"
          if [ -f package.json ]; then
            npm ci
            npm test --if-present
          else
            echo "No JS tests for ${{ matrix.svc }}"
          fi

      - name: Set tags
        id: tags
        run: |
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "tags=${{ env.ACR_LOGIN_SERVER }}/${{ steps.paths.outputs.image }}:${GITHUB_SHA},${{ env.ACR_LOGIN_SERVER }}/${{ steps.paths.outputs.image }}:latest" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.paths.outputs.dir }}
          push: ${{ github.event_name != 'pull_request' }}  # push only on branch pushes
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
